### PR TITLE
change from Subgroups to Working Groups

### PR DESCRIPTION
**Pull request by pdp2shirts**
Signed-off-by: Paul Pindell <ppindell@gmail.com>

### CODE REVIEW

**Review by seroyer — APPROVED** [review]
Along these lines, should "Outreach Committee" become just "Outreach"?

**Comment by pdp2shirts** [comment]
@opiproject/opi-maintainers can we merge this after the discussion in TSC? I'll submit another PR to change Outreach Committee to Outreach Working Group.

**Comment by seroyer** [comment]
> 

It's fine with me.  I was just looking for another @opiproject/opi-maintainers to +1 before merging.

**Review by glimchb — APPROVED** [review]
lgtm

**Pull request merged**
