### PR TITLE
Linux Foundation: Support OPI moving into LF

### PR DESCRIPTION
**Pull request by mestery**
These changes are to support the Open Programmable Infrastructure
Project moving into the Linux Foundation.

Signed-off-by: Kyle Mestery <mestery@mestery.com>

### CODE REVIEW

**Comment by mestery** [comment]
FYI @tbenzies

**Review by glimchb — APPROVED** [review]
lgtm

**Review by seroyer — APPROVED** [review]

**Review by sandersms — COMMENTED** [review]
Looks good

**Review by sandersms — APPROVED** [review]

**Comment by mestery** [comment]
Lets hold merging this one until next week when OPI launches.

**Review by pdp2shirts — CHANGES_REQUESTED** [review]
In the members/index.md the members listed ought to be referred to as "Premier" members not "Platinum" members.

**Comment by mestery** [comment]
@pdp2shirts I incorporated your changes when I had to force push this PR. Can you remove your `request changes` vote so we can merge this next week on launch day? Thanks!

**Review by pdp2shirts — APPROVED** [review]

**Comment by pdp2shirts** [comment]
> 

@mestery did I do that correctly or is there something else I need to do to remove the request changes

**Comment by mestery** [comment]
> Also we will need to add the Nvidia logo to the list of premier members. They have started and will complete process to join by tomorrow

I'm getting their logo and any other late joiners from LF today. Plenty of time to update this before Tuesday.

**Pull request merged**
